<?php
/**
 * Built-in defaults for password_vpop_recovery.
 *
 * This file ships with the plugin and is loaded FIRST (see init() in
 * password_vpop_recovery.php), before the real config.inc.php. It contains
 * no secrets and no per-install data on purpose, so it's safe to keep in
 * git and to overwrite on every upgrade.
 *
 * config.inc.php (per-install, gitignored) is loaded AFTER this file and
 * only needs to declare what differs from these defaults — Roundcube's own
 * config merge overwrites a key here with the same key from config.inc.php
 * when both are set, so there's nothing to keep in sync by hand.
 *
 * Do not edit this file for a specific install — use config.inc.php instead
 * (copy config.inc.php.dist to get started).
 */

// This adaptation stores its data in Roundcube's OWN database (no separate
// DB connection needed, so pr_db_dsn is intentionally left unset).
$config['pr_users_table'] = 'password_recovery_data';

$config['pr_fields'] = [
    'altemail' => 'alt_email',
];

// Verification method: confirmation code by alternate email only.
$config['pr_use_question'] = false;
$config['pr_use_confirm_code'] = true;

// Confirmation code settings
$config['pr_confirm_code_length'] = 6;
$config['pr_confirm_code_count_max'] = 3;
$config['pr_confirm_code_validity_time'] = 30; // minutes

// The password change is always delegated to the 'password' plugin.
$config['pr_use_password_plugin'] = true;
$config['pr_password_minimum_length'] = 8;
$config['pr_password_minimum_score'] = 1;

// How the recovery flow actually resets the password on the mail server:
//   'vpopmaild' - connect to vpopmaild as a domain postmaster and run
//                 mod_user/clear_text_password (default; works with any
//                 vpopmail install, SQL-backed or not).
//   'sql'       - write directly to vpopmail's own SQL table. Only useful
//                 when vpopmail itself uses a SQL backend; needs pr_sql_*
//                 configured in config.inc.php.
$config['pr_password_driver'] = 'vpopmaild';

// Only used when pr_password_driver = 'sql'. pr_sql_dsn is NOT set here (must
// be defined in config.inc.php, it's a secret - same DSN format as Roundcube's
// own db_dsnw, e.g. 'mysql://user:pass@host/dbname', since this reuses
// rcube_db, just pointed at a different database - vpopmail's own, normally
// on a separate server); the table/column/hash-scheme defaults below match
// vpopmail's own default MySQL schema and can be overridden per install if it
// differs.
$config['pr_sql_table'] = 'vpopmail';
$config['pr_sql_columns'] = [
    'user'         => 'pw_name',
    'domain'       => 'pw_domain',
    'passwd'       => 'pw_passwd',
    'clear_passwd' => 'pw_clear_passwd',
];

// 'crypt-md5', 'crypt-blowfish', 'sha512-crypt', or 'system' (traditional
// DES crypt - only useful for very old vpopmail builds; 8-character
// passwords effectively). MUST match how your vpopmail was compiled/patched
// - see README, "SQL driver".
$config['pr_sql_hash_scheme'] = 'sha512-crypt';

// Whether to also write the plaintext password into pw_clear_passwd
// (needed only for APOP/CRAM-MD5; leave false unless you know you need it).
$config['pr_sql_store_clear'] = false;

// Multi-domain: by default, when a domain in pr_domains doesn't declare its
// own SMTP account, the confirmation email is sent authenticating via SMTP
// AUTH as that domain's own postmaster@<domain>, reusing the same password
// configured for vpopmaild admin access (vpopmail shares one password across
// IMAP/POP/SMTP-AUTH for a mailbox). Set to false to send unauthenticated
// (only if your relay allows it) unless overridden per domain.
$config['pr_smtp_auth_default'] = true;

// From/Reply-To address for the confirmation-code email. This is just the
// LOCAL PART (default 'noreply'), not a full address - it gets combined
// with the domain being recovered (<local-part>@<domain>) unless a domain
// sets its own 'from' or 'smtp_user' in pr_domains. A single fixed address
// hardcoded to one domain would commonly get rejected by another domain's
// unauthenticated relay and hurts SPF/DKIM anyway. If this DOES contain
// '@' it's used as-is everywhere instead, for installs that genuinely want
// one fixed address.
$config['pr_replyto_email'] = 'noreply';

// Real, DB-backed rate limiting (independent of session/cookies).
$config['pr_recovery_attempts_table'] = 'password_recovery_attempts';
$config['pr_rate_limit_account_per_day'] = 5;
$config['pr_rate_limit_ip_per_day'] = 20;

// How long to keep rows in pr_recovery_attempts_table before they're
// opportunistically deleted (each insert has a 1-in-200 chance of also
// running the cleanup, so no cron is needed). Floored at 1 day - the
// rate-limit checks above only look back 24h, so anything shorter would
// risk deleting rows the rate limit itself still needs. Longer than that
// is purely an audit-trail vs. table-size tradeoff for the admin to make.
$config['pr_recovery_attempts_retention_days'] = 7;

// Logging
$config['pr_password_log'] = true;
$config['pr_debug'] = false;

?>
